name: build

on:
  workflow_run:
    workflows: [tests]
    branches: [master]
    types: [completed]

jobs:

  build:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'

    strategy:
      fail-fast: true
      matrix:
        version: [py37, py38, py39]

    steps:

    - name: Checkout changes
      uses: actions/checkout@v2.3.4

    - name: Login to docker hub
      run: make login TOKEN=${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and upload an image
      run: make upload TAG=${{ matrix.version }}


