name: build

on:
  workflow_run:
    workflows: [tests]
    branches: [master]
    types: [completed]

concurrency:
  group: build-${{ github.event.workflow_run.head_branch  }}
  cancel-in-progress: true

jobs:

  build:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'

    strategy:
      fail-fast: true
      matrix:
        include:

          - tag: py37
            py-version: '3.7'
            build-image: muffin

          - tag: py37-node
            py-version: '3.7'
            build-image: muffin-node
            base-tag: py37

          - tag: py38
            py-version: '3.8'
            build-image: muffin

          - tag: py38-node
            py-version: '3.8'
            build-image: muffin-node
            base-tag: py38

          - tag: py39
            py-version: '3.9'
            build-image: muffin

          - tag: py39-node
            py-version: '3.9'
            build-image: muffin-node
            base-tag: py39

          - tag: py310
            py-version: '3.10'
            build-image: muffin

          - tag: py310-node
            py-version: '3.10'
            build-image: muffin-node
            base-tag: py310

          - tag: latest
            py-version: '3.9'
            build-image: muffin

          - tag: latest-node
            py-version: '3.9'
            build-image: muffin-node
            base-tag: py39

    steps:

    - name: Checkout changes
      uses: actions/checkout@main

    - uses: satackey/action-docker-layer-caching@main
      continue-on-error: true

    - name: Login to docker hub
      run: make login PASSWORD=${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and upload images
      run: make upload TAG=${{ matrix.tag }} PY_VERSION=${{ matrix.py-version }} BUILD_IMAGE=${{ matrix.build-image }} BASE_TAG=${{ matrix.base-tag }}

  notify:
    runs-on: ubuntu-latest
    needs: build
    steps:

    - name: Notify Success
      uses: archive/github-actions-slack@master
      with:
          slack-channel: C2CRL4C4V
          slack-text: "*[${{ github.repository }}]* build is success *(${{ github.ref }})* https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_TOKEN }}
          slack-optional-as_user: false
          slack-optional-icon_emoji: ":white_check_mark:"
