name: build

on:
  workflow_run:
    workflows: [tests]
    branches: [master]
    types: [completed]

concurrency:
  group: build-${{ github.event.workflow_run.head_branch  }}
  cancel-in-progress: true

jobs:
  build-base:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'

    strategy:
      fail-fast: true
      matrix:
        py-version:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"

    steps:
      - name: Checkout changes
        uses: actions/checkout@main

      - uses: satackey/action-docker-layer-caching@main
        continue-on-error: true

      - name: Login to docker hub
        run: make login PASSWORD=${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and upload images
        run: make upload BUILD_IMAGE=muffin PY_VERSION=${{ matrix.py-version }}

  build-node:
    runs-on: ubuntu-latest
    needs: build-base

    strategy:
      fail-fast: true
      matrix:
        py-version:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"

    steps:
      - name: Checkout changes
        uses: actions/checkout@main

      - uses: satackey/action-docker-layer-caching@main
        continue-on-error: true

      - name: Login to docker hub
        run: make login PASSWORD=${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and upload images
        run: make upload BUILD_IMAGE=muffin-node PY_VERSION=${{ matrix.py-version }}

  mark-latest:
    runs-on: ubuntu-latest
    needs: build-node

    strategy:
      fail-fast: true
      matrix:
        py-version:
          - "3.12"

    steps:
      - name: Login to docker hub
        run: |
          echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u horneds --password-stdin

      - run: |
          docker pull horneds/muffin:py${{ matrix.py-version }}
          docker pull horneds/muffin-node:py${{ matrix.py-version }}
          docker tag horneds/muffin:py${{ matrix.py-version }} horneds/muffin:latest
          docker tag horneds/muffin-node:py${{ matrix.py-version }} horneds/muffin-node:latest
          docker push horneds/muffin:latest
          docker push horneds/muffin-node:latest
