name: tests

on:
  pull_request:
  push:

jobs:

  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        tag: [py37, py38, py39]

    steps:

    - name: Checkout changes
      uses: actions/checkout@v2.3.4

    - name: Set up Python
      uses: actions/setup-python@v2.2.2

    - name: Install requirements
      run: pip install -r requirements.txt

    - uses: satackey/action-docker-layer-caching@v0.0.11
      continue-on-error: true

    - name: Build Image
      run: make ${{ matrix.tag }}

    - name: Test with pytest
      run: pytest tests --tag ${{ matrix.tag }}
