name: tests

on:
  pull_request:
  push:

jobs:

  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        tag:
        - py39
        - py310
        - py311
        - py312

    steps:

    - name: Checkout changes
      uses: actions/checkout@main

    - name: Set up Python
      uses: actions/setup-python@main
      with:
        python-version: '3.11'
        cache: pip

    - name: Install requirements
      run: pip install -r requirements.txt

    - name: Build Image
      run: make ${{ matrix.tag }}

    - name: Test with pytest
      run: pytest tests --tag ${{ matrix.tag }}

  notify:
    runs-on: ubuntu-latest
    needs: tests
    steps:

    - name: Notify Success
      uses: archive/github-actions-slack@master
      with:
          slack-channel: C2CRL4C4V
          slack-text: "*[${{ github.repository }}]* tests are passed *(${{ github.ref }})* https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_TOKEN }}
          slack-optional-as_user: false
          slack-optional-icon_emoji: ":white_check_mark:"
